### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by Neurrone** [zboxfs/zbox#12]
Would love to be able to use this.

**Comment by burmecia** [comment]
Thanks. Feature branch [feature-win](https://github.com/zboxfs/zbox/tree/feature-win) has been created in regarding this issue.

**Comment by burmecia** [comment]
Since Rust and libsodium are already cross-platform, the most parts of Zbox should be able to run on Windows without problem.

The only uncertain part is 'Path' and 'PathBuf', because that module is platform-dependent, I am not sure how it would be using separator '/' on Windows. Other than that, I can't see any other major obstacles to support Windows.

**Comment by Neurrone** [comment]
The [Path module ](https://doc.rust-lang.org/std/path/index.html) looks quite cross-platform, though I'm only starting to learn Rust as well, so can't say for sure. For other filesystem libraries, I've never had problems using / as the path separator on Windows, so unless it accesses an OS specific directory like /tmp etc, it shouldn't be an issue.
