### ISSUE TITLE
Why is Zbox so slow?

### ISSUE THREAD

**Issue by tatetian** [zboxfs/zbox#24]
The benchmark results in README show that Zbox's read/write throughput is one order of magnitude lower than the baseline. And my impression is that AES-GCM can easily achieve a throughput over 1GB/s. So, encryption/decryption should not be the root of the problem. Then, **what is the performance bottleneck? Is it the Merkle trees (if Zbox uses them internally)? Is improving performance on the top of your TODO list?** 

I believe Zbox is a very good idea. And it could be even more useful if the performance overhead is reduced to the minimal.

There are no design docs about the internals of Zbox. And I haven't got the time to read the source code. So, I hope you can shed some light on the performance issue. Thanks.

**Comment by burmecia** [comment]
Yes, you're right.

The performance has always been an issue since its first release last year. Initially the performance was even worse, only 2 digits number MB/s! The main bottleneck at that time was content hash calculation, which reads whole file content for hashing even for a tiny change. After introduced Merkle tree, I don't think that is still bottleneck as the hash calculation time is greatly reduced and performance went up to 100+ MB/s. But even that is still not optimal compared with the baseline.

As for now, I suspect the bottleneck is the internal buffer size. Especially for reading, because it doesn't involve too many layers. The speed should be close to the decompression and decryption, which normally are hundreds of MB/s. The reason is because I'm quite conservative on setting buffer size, I always set to minimal size and then adjust it when performance become issue.

Improving performance is on the 2nd of TODO list, along with other tasks such as volume refactoring, Python/NodeJS binding, supporting kev-value store and etc. I am currently rewriting the volume structure which will be simplified and can easily support more storage. I hope it will also bring some performance benefits. After that is done, I will then focus on performance and try to minimize the binary size.

The design doc is definitely something I need to put more works on, but to reduce unnecessary re-work I think it is better to start it after the whole architecture was stabilized. 

Thanks for your questions!

**Comment by burmecia** [comment]
Make compression layer optional is a good idea, I will note it down on the TODO list. I'm also glad to see how Zbox will performs in real application. And thanks again for your reply and if you have any questions just let me know.

**Comment by burmecia** [comment]
In the latest version 0.6.0, performance has been improved a lot. The volume and storage have been dramatically rewritten. Thanks to this new design, read speed can achieve 300-400 MB/s now. Compression is also optional now.
