### ISSUE TITLE
no std support?

### ISSUE THREAD

**Issue by hydra007** [zboxfs/zbox#28]
I am really interested in using zbox as the default file system for [my OS](https://github.com/hydra007/Project-Longhorn), but can it be used in no std environments? I took a look at a couple pieces of your code and saw nowhere a no std indicator. Your project claims to be embeddable, but it isn't truly embeddable if you can't use it in those environments. If this is a project GOAL, great, and I would be willing to help to the best of my ability. If not, oh well. Great work so far though! :)

**Comment by burmecia** [comment]
You're right, no std hasn't been support yet, although I wish it could be implemented in the future but that is not my priority at this moment.As regarding the embeddable meaning, it is more on application side, that is, running inside application memory space to minimize data leak. It can be used in the true "embeddable" environment, but like you said it must enable no std first. If you could help on that, it will be really appreciated.Thanks.-------- Original Message --------Subject: [zboxfs/zbox] no std support? (#28)From: hydra007 To: zboxfs/zbox CC: Subscribed I am really interested in using zbox as the default file system for my OS, but can it be used in no std environments? I took a look at a couple pieces of your code and saw nowhere a no std indicator. Your project claims to be embeddable, but it isn't truly embeddable if you can't use it in those environments. If this is a project GOAL, great, and I would be willing to help to the best of my ability. If not, oh well. Great work so far though! :)

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/zboxfs/zbox","title":"zboxfs/zbox","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/zboxfs/zbox"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"no std support? (#28)"}],"action":{"name":"View Issue","url":"https://github.com/zboxfs/zbox/issues/28"}}}
{"@type":"MessageCard","@context":"http://schema.org/extensions","hideOriginalBody":"false","originator":"37567f93-e2a7-4e2a-ad37-a9160fc62647","title":"no std support? (#28)","sections":[{"text":"","activityTitle":"**hydra007**","activityImage":"https://avatars2.githubusercontent.com/u/33503692?s=160\u0026v=4","activitySubtitle":"@hydra007","facts":[{"name":"Repository: ","value":"zboxfs/zbox"},{"name":"Issue #: ","value":28}]}],"potentialAction":[{"name":"Add a comment","@type":"ActionCard","inputs":[{"isMultiLine":true,"@type":"TextInput","id":"IssueComment","isRequired":false}],"actions":[{"name":"Comment","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueComment\",\"repositoryFullName\":\"zboxfs/zbox\",\"issueId\":28,\"IssueComment\":\"{{IssueComment.value}}\"}"}]},{"name":"Close issue","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueClose\",\"repositoryFullName\":\"zboxfs/zbox\",\"issueId\":28}"},{"targets":[{"os":"default","uri":"https://github.com/zboxfs/zbox/issues/28"}],"@type":"OpenUri","name":"View on GitHub"},{"name":"Unsubscribe","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"MuteNotification\",\"threadId\":334374501}"}],"themeColor":"26292E"}
